[package]
name = "qapi-old-hack"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]
