[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde_json = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.qapi]
path = "../../projects/qapi"
