[package]
name = "qapi-spec-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
heck = "0.5.0"
nom = "7"
prettyplease = "0.2.22"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
